# Predicting Tennis Match Winners and Losers
#### AIT580 
#### Final Class Project
- Hunter Walden, Kevin Mitchell, Jason Myslewski
- 13 July 2022

## Introduction

## Purpose

## Methods

### Column Name Meanings:

**Attribute Information:**

1. Player 1 Name of Player 1
2. Player 2 Name of Player 2
3. Result Result of the match (0/1) - Referenced on Player 1 is Result = 1 if Player 1 wins (FNL.1>FNL.2)
4. FSP.1 First Serve Percentage for player 1 (Real Number)
5. FSW.1 First Serve Won by player 1 (Real Number)
6. SSP.1 Second Serve Percentage for player 1 (Real Number)
7. SSW.1 Second Serve Won by player 1 (Real Number)
8. ACE.1 Aces won by player 1 (Numeric-Integer)
9. DBF.1 Double Faults committed by player 1 (Numeric-Integer)
10. WNR.1 Winners earned by player 1 (Numeric)
11. UFE.1 Unforced Errors committed by player 1 (Numeric)
12. BPC.1 Break Points Created by player 1 (Numeric)
13. BPW.1 Break Points Won by player 1 (Numeric)
14. NPA.1 Net Points Attempted by player 1 (Numeric)
15. NPW.1 Net Points Won by player 1 (Numeric)
16. TPW.1 Total Points Won by player 1 (Numeric)
17. ST1.1 Set 1 result for Player 1 (Numeric-Integer)
18. ST2.1 Set 2 Result for Player 1 (Numeric-Integer)
19. ST3.1 Set 3 Result for Player 1 (Numeric-Integer)
20. ST4.1 Set 4 Result for Player 1 (Numeric-Integer)
21. ST5.1 Set 5 Result for Player 1 (Numeric-Integer)
22. FNL.1 Final Number of Games Won by Player 1 (Numeric-Integer)
23. FSP.2 First Serve Percentage for player 2 (Real Number)
24. FSW.2 First Serve Won by player 2 (Real Number)
25. SSP.2 Second Serve Percentage for player 2 (Real Number)
26. SSW.2 Second Serve Won by player 2 (Real Number)
27. ACE.2 Aces won by player 2 (Numeric-Integer)
28. DBF.2 Double Faults committed by player 2 (Numeric-Integer)
29. WNR.2 Winners earned by player 2 (Numeric)
30. UFE.2 Unforced Errors committed by player 2 (Numeric)
31. BPC.2 Break Points Created by player 2 (Numeric)
32. BPW.2 Break Points Won by player 2 (Numeric)
33. NPA.2 Net Points Attempted by player 2 (Numeric)
34. NPW.2 Net Points Won by player 2 (Numeric)
35. TPW.2 Total Points Won by player 2 (Numeric)
36. ST1.2 Set 1 result for Player 2 (Numeric-Integer)
37. ST2.2 Set 2 Result for Player 2 (Numeric-Integer)
38. ST3.2 Set 3 Result for Player 2 (Numeric-Integer)
39. ST4.2 Set 4 Result for Player 2 (Numeric-Integer)
40. ST5.2 Set 5 Result for Player 2 (Numeric-Integer)
41. FNL.2 Final Number of Games Won by Player 2 (Numeric-Integer)
42. Round Round of the tournament at which game is played (Numeric-Integer)

## Part 1: Data Cleaning

#### Data Cleaning Checklist
1. Import data sets
2. Combine data sets?
3. Rename columns?
3. Check for consistency in data types. 
4. Check for and determine how to handle missing data
5. Check for outliers
6. Does the data layout in its current form make sense for exploration?
7. Check for duplicate rows
8. Validate and create the final data set.

In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# import csv files
ausMen = pd.read_csv("AusOpen-men-2013.csv")
ausWomen = pd.read_csv("AusOpen-women-2013.csv")
frenchMen = pd.read_csv("FrenchOpen-men-2013.csv")
frenchWomen = pd.read_csv("FrenchOpen-women-2013.csv")
usMen = pd.read_csv("USOpen-men-2013.csv")
usWomen = pd.read_csv("USOpen-women-2013.csv")
WimbMen = pd.read_csv("Wimbledon-men-2013.csv")
WimbWomen = pd.read_csv("Wimbledon-women-2013.csv")

In [13]:
# rename columns for consistency
ausMen = ausMen.rename(columns={'FNL1': 'FNL.1', 'FNL2': 'FNL.2'})
ausWomen = ausWomen.rename(columns={'FNL1': 'FNL.1', 'FNL2': 'FNL.2'})
usMen = usMen.rename(columns={'FNL1': 'FNL.1', 'FNL2': 'FNL.2'})
usWomen = usWomen.rename(columns={'ST2.1.1': 'ST1.2', 'Player 1': 'Player1', 'Player 2': 'Player2', 'ROUND':'Round'})
WimbWomen = WimbWomen.rename(columns={'ST1.1.1': 'ST1.2'})

In [14]:
dfs = [ausMen, ausWomen, frenchMen, frenchWomen, usMen, usWomen, WimbMen, WimbWomen]

for d in dfs:
    print(d.columns)

Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')
Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')
Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')
Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')
Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')
Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')
Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')
Index(['Player1', 'Player2', 'Round', 'Result', 'FNL.1', 'FNL.2', 'FSP.1',
       'FSW.1', 'SSP.1', 'SSW.1', 'ACE.1', 'DBF.1', 'WNR.1', 'UFE.1', 'BPC.1',
       'BPW.1', 'NPA.1', 'NPW.1', 'TPW.1', 'ST1.1', 'ST2.1', 'ST3.1', 'ST4.1',
       'ST5.1', 'FSP.2', 'FSW.2', 'SSP.2', 'SSW.2', 'ACE.2', 'DBF.2', 'WNR.2',
       'UFE.2', 'BPC.2', 'BPW.2', 'NPA.2', 'NPW.2', 'TPW.2', 'ST1.2', 'ST2.2',
       'ST3.2', 'ST4.2', 'ST5.2'],
      dtype='object')

In [15]:
# look at the shape of each individual data frame. 
for d in dfs:
    print(d.shape)

(126, 42)
(127, 42)
(125, 42)
(127, 42)
(126, 42)
(76, 42)
(114, 42)
(122, 42)

In [17]:
# concatentate all 8 data frames into one. 
df = pd.concat(dfs)

In [18]:
# review the column data 
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 943 entries, 0 to 121
Data columns (total 42 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Player1  943 non-null    object
 1   Player2  943 non-null    object
 2   Round    943 non-null    int64
 3   Result   943 non-null    int64
 4   FNL.1    942 non-null    float64
 5   FNL.2    942 non-null    float64
 6   FSP.1    943 non-null    int64
 7   FSW.1    943 non-null    int64
 8   SSP.1    943 non-null    int64
 9   SSW.1    943 non-null    int64
 10  ACE.1    921 non-null    float64
 11  DBF.1    935 non-null    float64
 12  WNR.1    817 non-null    float64
 13  UFE.1    817 non-null    float64
 14  BPC.1    942 non-null    float64
 15  BPW.1    942 non-null    float64
 16  NPA.1    859 non-null    float64
 17  NPW.1    860 non-null    float64
 18  TPW.1    631 non-null    float64
 19  ST1.1    942 non-null    float64
 20  ST2.1    939 non-null    float64
 21  ST3.1    622 non-null    float64
 22  ST4.1    221 non-null    float64
 23  ST5.1    86 non-null     float64
 24  FSP.2    943 non-null    int64
 25  FSW.2    943 non-null    int64
 26  SSP.2    943 non-null    int64
 27  SSW.2    943 non-null    int64
 28  ACE.2    921 non-null    float64
 29  DBF.2    935 non-null    float64
 30  WNR.2    817 non-null    float64
 31  UFE.2    817 non-null    float64
 32  BPC.2    942 non-null    float64
 33  BPW.2    942 non-null    float64
 34  NPA.2    859 non-null    float64
 35  NPW.2    860 non-null    float64
 36  TPW.2    631 non-null    float64
 37  ST1.2    942 non-null    float64
 38  ST2.2    939 non-null    float64
 39  ST3.2    622 non-null    float64
 40  ST4.2    221 non-null    float64
 41  ST5.2    86 non-null     float64
dtypes: float64(30), int64(10), object(2)
memory usage: 316.8+ KB

In [22]:
# view a sample of the dataframe.
df.sample(15)

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2
74,D.Brown,L.Hewitt,2,1,3.0,1.0,64,71,36,25,...,10.0,1.0,34.0,15.0,NaN,4.0,4.0,7.0,2.0,NaN
122,Andy Murray,Stanislas Wawrinka,1,0,0.0,3.0,63,37,37,22,...,4.0,11.0,31.0,42.0,107.0,6.0,6.0,6.0,NaN,NaN
74,P.Cetkovska,C.Wozniacki,2,1,2.0,0.0,71,31,29,7,...,6.0,0.0,8.0,4.0,NaN,2.0,2.0,NaN,NaN,NaN
113,Florian Mayer,David Ferrer,4,0,1.0,3.0,61,52,39,27,...,9.0,19.0,19.0,27.0,153.0,6.0,7.0,6.0,6.0,NaN
100,Florian Mayer,Jerzy Janowicz,3,1,3.0,0.0,68,42,32,15,...,0.0,1.0,11.0,15.0,63.0,5.0,2.0,2.0,NaN,NaN
14,Alejandro Falla,Mikhail Kukushkin,1,1,3.0,1.0,60,50,40,23,...,4.0,14.0,NaN,NaN,128.0,7.0,2.0,2.0,3.0,NaN
58,R.Berankis,P-H.Mathieu,1,0,1.0,3.0,52,73,48,36,...,10.0,3.0,35.0,29.0,NaN,7.0,7.0,6.0,6.0,NaN
29,Jan Hajek,Damir Dzumhur,1,0,0.0,3.0,73,31,27,6,...,7.0,12.0,NaN,NaN,95.0,6.0,6.0,6.0,NaN,NaN
57,O.Puchkova,A.Rus,1,1,2.0,0.0,69,24,31,4,...,5.0,4.0,9.0,6.0,NaN,4.0,2.0,NaN,NaN,NaN
79,Mona Barthel,Luksika Kumkhum,2,1,2.0,1.0,63,44,37,18,...,3.0,7.0,7.0,8.0,94.0,6.0,3.0,4.0,NaN,NaN
12,Eugenie Bouchard,Hao Chen Tang,1,1,2.0,0.0,64,30,36,16,...,2.0,7.0,NaN,NaN,64.0,5.0,1.0,NaN,NaN,NaN
54,A.Haider-Maurer,G.Soeda,1,0,0.0,3.0,56,43,44,18,...,9.0,5.0,21.0,14.0,NaN,7.0,7.0,6.0,NaN,NaN
0,M.Koehler,V.Azarenka,1,0,0.0,2.0,60,21,40,8,...,16.0,6.0,8.0,4.0,NaN,6.0,6.0,NaN,NaN,NaN
108,L.Kubot,J.Janowicz,5,0,0.0,3.0,57,44,43,20,...,10.0,3.0,16.0,12.0,NaN,7.0,6.0,6.0,NaN,NaN
68,L Robson,L Dominguez Lino,1,1,2.0,0.0,57,27,43,7,...,9.0,3.0,5.0,4.0,NaN,5.0,0.0,NaN,NaN,NaN

In [24]:
# check for duplicate rows:
df.duplicated().value_counts()

False    943
dtype: int64

In [25]:
# save the processed data set that we will use for exploratory analysis
df.to_csv('MasterDF.csv')

## Part 2: Exploratory Analysis

## Part 3: Predictive Analysis

## Part 4: Conclusion

## Part 5: References